config/routes.rb
ProjectBernies::Application.routes.draw do
  root 'home#index'


  resources :pictures, only: [:new, :create, :update]

  resources :artifacts , only:[:new, :create, :show, :index] do
    collection do
      get 'explore'
    end
  end

  resources :artifacts do
    put "upvote", :to => "artifacts#upvote", as: :upvote
    put "downvote", :to => "artifacts#downvote", as: :downvote
  end

  patch 'artifacts/:artifact_id', to: 'artifacts#update'
  patch 'artifacts/:artifact_id/pictures/:picture_id', to: 'pictures#update', as: 'artifact_picture'
  get 'pictures/neighbors', to: 'pictures#neighbors', constraints: {format: 'json'}
  get 'neighborhoods/find', to: 'neighborhoods#find', constraints: {format: 'json'}
  get 'neighborhoods', to: 'neighborhoods#all', constraints: {format: 'json'}
  get 'neighborhoods/:id', to: 'neighborhoods#show', as: 'neighborhood'
end

app/models/artifact.rb
require 'net/http'
require 'json'

class Artifact < ActiveRecord::Base
  belongs_to :neighborhood

  has_many :pictures
  has_many :reflections

  has_many :artifact_tags
  has_many :tags, through: :artifact_tags

  before_create :update_neighborhood_counter_cache
  before_save :update_neighborhood_counter_cache

  scope :near, -> (latitude, longitude, distance_in_meters = 250) {
    where(%{
      ST_DWithin(
        ST_GeographyFromText(
          'SRID=4326;POINT(' || artifacts.longitude || ' ' || artifacts.latitude || ')'
        ),
        ST_GeographyFromText('SRID=4326;POINT(%f %f)'),
        %d
      )
    } % [longitude, latitude, distance_in_meters])
    .order(%{
      'SRID=4326;POINT(' || artifacts.longitude || ' ' || artifacts.latitude || ')' <->
      'SRID=4326;POINT(%f %f)'
    } % [longitude, latitude])
  }

  scope :contained_within, -> (geom) {
    where(%{
      ST_Within(
        ST_GeomFromText(
          'SRID=4326;POINT(' || artifacts.longitude || ' ' || artifacts.latitude || ')'
        ),
        '%s'
      )
    } % [geom])
  }

  def neighbors(radius=nil)
    if radius
      Artifact.near(self.latitude, self.longitude, radius)
    else
      Artifact.near(self.latitude, self.longitude)
    end
  end

  def neighborhood
    Neighborhood.containing(self.latitude, self.longitude).first if self.latitude && self.longitude
  end

  def canonical_picture
    self.pictures.first
  end

  def picture_urls
    self.pictures.map {|p| p.image.preview.url }
  end

  def to_map_marker
    image = self.canonical_picture.image
    { lat: self.latitude,
      lng: self.longitude,
      picture_count: self.pictures.count,
      map_thumb: image.map_thumb.url,
      info_thumb: image.map_show.url,
      show_url: "/artifacts/#{self.id}"
    }
  end

  def self.all_with_picture
    # this could be optimized
    self.all.select { |a| a.pictures.count > 0 }
  end

  def post_311_request
    uri = URI.parse('http://test311request.cityofchicago.org/open311/v2/requests.json')

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({'api_key' => 'b8c991cbe23fb49180b59c8744d24824',
                           'service_code'=> '4fd3b167e750846744000005',
                           'lat' => self.latitude.to_f,
                           'long'=> self.longitude.to_f,
                           'address_string' => "123 Test Street",
                           'description' => "Test description, Leon strikes again",
                           'attribute[WHEREIS1]'=> "FRONT",
                           'attribute[WHATTYP2]'=> "UNK",
                           'attribute[OVER6FEE]' => 'NO'})

    response = http.request(request)
    msg = response.body

    JSON.parse(msg).pop["token"]
  end

  def request_status
    uri = URI.parse("http://test311request.cityofchicago.org/open311/v2/requests/#{self.open311_token}.json")

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)

    response = http.request(request)
    msg = response.body
    JSON.parse(msg)
  end

  private

  def update_neighborhood_counter_cache
    if neighborhood = self.neighborhood
      neighborhood.update_cache
    end
  end
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  def index
    @artifacts = Artifact.all_with_picture
  end

  def explore
    @artifacts = Artifact.all_with_picture
  end

  def new
  end

  def create
  end

  def show
    @picture = Picture.new
    @artifact = Artifact.find(params[:id])
  end

  def update
  end

  def upvote
    @artifact = Artifact.find(params[:artifact_id])
    unless @artifact.is_reported
      @artifact.votes += 1
      @artifact.save
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def downvote
    @artifact = Artifact.find(params[:artifact_id])
    unless @artifact.is_reported
      @artifact.votes -= 1
      @artifact.save

      if @artifact.votes.to_i <= -10 && @artifact.is_reported == false
        @artifact.open311_token = @artifact.post_311_request
        @artifact.is_reported = true
        @artifact.save!
      end

      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_gallery.html.erb
<div id="thumbs-box">
    <% @artifacts.each do |art| %>
    <div class="thumb-box">
      <div class="thumb"><a href="/artifacts/<%= art.id %>"><%= image_tag art.canonical_picture.image.preview.url %></a></div>

      <div class="info"><%= art.pictures.count %> <%= image_tag("/images/pics_rev.png", class: "extra-small-icon")%><div class="likes right"><%= art.votes %> <%= image_tag("/images/heart_rev.png", class: "extra-small-heart")%></div></div>
    </div>
  <% end %>
</div>

app/views/artifacts/downvote.js.erb
$("#counter").html("<%= pluralize(@artifact.votes, 'vote') %>");
$(".upvote").hide();
$(".downvote").hide();

app/views/artifacts/explore.html.erb
<%= javascript_include_tag :artifacts %>
<%= javascript_include_tag :upload %>

<div id="map"></div>
<%= render "layouts/uploader" %>

<script>
  var artifacts = <%= raw @artifacts.map(&:to_map_marker).to_json %>;
</script>


<% unless mobile_device? %>
<script>
    $(document).ready(function(){
      $('body').addClass('map-page');
    })
</script>
<% end %>

app/views/artifacts/index.html.erb
<%= javascript_include_tag :upload %>

<div class="container">
  <div id="headings">
    <% if !mobile_device? %>
      <h1 class="center">
        <%= "It's art. Deal with it." %>
      </h1>
      <div class="separator center"><%= image_tag '/images/dk_separator_01.png' %></div>
    <% end %>
    <h2  class="center">Explore. Discover. Share. Vote.</h2>
  </div>

  <%= render "layouts/uploader" %>
  <%= render 'artifacts/gallery' %>
</div>

app/views/artifacts/show.html.erb
<%= javascript_include_tag :upload %>
<%= javascript_include_tag :artifacts_show %>

<div class="container">

  <%= render "layouts/uploader" %>

  <div id="info-bar">
    <div id="neighborhood" class="left">
      <h2><%= image_tag "/images/marker_rev.png", class: "small-icon" %>
        <% if neighborhood = @artifact.neighborhood %>
          <%= link_to neighborhood.name, neighborhood_path(neighborhood) %>
        <% else %>
          <%= 'In the Wild' %>
        <% end %>
      </h2>
    </div>

    <% unless @artifact.votes.to_i <= -10 %>
      <div id="votes" class="right">
        <span id="counter"><%= @artifact.votes %></span>

        <%= link_to (image_tag("/images/heart_rev.png", class: "small-icon")), artifact_upvote_path(@artifact), remote: true, method: "put", class: "upvote" %>
        <%= link_to (image_tag("/images/broken_heart_rev.png", class: "small-icon")), artifact_downvote_path(@artifact), remote: true, method: "put", class: "downvote" %>
      </div>
    <% end %>
  </div>

  <% if @artifact.is_reported %>
    <div id="flagged-artifact">
        <p>This piece of so-called "art" has been flagged for removal with the City of Chicago.</p>
        <p>Service Request ID: <span id="service-id">
          <%= link_to "##{@artifact.request_status.pop["service_request_id"]}", "http://servicetracker.cityofchicago.org/requests/#{@artifact.request_status.pop["service_request_id"]}" %></span>
           Request Status: <span id="service-status"><%= @artifact.request_status.pop["status"].capitalize %></span></p>
    </div>
  <% end %>

  <div id="images" class="clear-both">
    <% if mobile_device? %>
    <div id="mini-map" class="mobile"></div>
    <div id="thumbs-box" class="mobile">
      <% @artifact.picture_urls.each do |pic| %>
      <div class="thumb-box">
        <div class="thumb"><%= image_tag pic %></div>
      </div>
      <% end %>
    </div>
    <% else %>
    <div id="mini-map" class="left one-third"></div>
    <div id="thumbs-box" class="right two-thirds">
      <% @artifact.picture_urls.each do |pic| %>
      <div class="thumb-box">
        <div class='thumb'><%= image_tag pic %></div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>


</div>

<script>
  var latitude = <%= @artifact.latitude %>
  var longitude = <%= @artifact.longitude %>
</script>

app/views/artifacts/upvote.js.erb
$("#counter").html("<%= pluralize(@artifact.votes, 'vote') %>");
$(".upvote").hide();
$(".downvote").hide();