config/routes.rb
ProjectBernies::Application.routes.draw do
  root 'home#index'


  resources :pictures, only: [:new, :create, :update]

  resources :artifacts , only:[:new, :create, :show, :index] do
    collection do
      get 'explore'
    end
  end

  resources :artifacts do
    put "upvote", :to => "artifacts#upvote", as: :upvote
    put "downvote", :to => "artifacts#downvote", as: :downvote
  end

  patch 'artifacts/:artifact_id', to: 'artifacts#update'
  patch 'artifacts/:artifact_id/pictures/:picture_id', to: 'pictures#update', as: 'artifact_picture'
  get 'pictures/neighbors', to: 'pictures#neighbors', constraints: {format: 'json'}
  get 'neighborhoods/find', to: 'neighborhoods#find', constraints: {format: 'json'}
  get 'neighborhoods', to: 'neighborhoods#all', constraints: {format: 'json'}
  get 'neighborhoods/:id', to: 'neighborhoods#show', as: 'neighborhood'
end

app/views/layouts/_header.html.erb
<div id="header">
    <div id="logo">
      <a href="/" title="ScrallWall" id="logo"></a>
    </div>
    <% if !mobile_device? %>
    <ul class="menu left">
      <li id="upload-menu-item">upload</li>
      <li><a href="#">about</a></li>
    </ul>
    <ul class="menu right">
      <li><%= link_to "artifacts", artifacts_path %></li>
      <li><%= link_to "explore", explore_artifacts_path %></li>
    </ul>
  <% else %>
    <ul class="menu-mobile">
      <li><a href="/">ScrallWall</a></li>
      <li><%= link_to "explore", explore_artifacts_path %></li>
      <li><%= link_to "artifacts", artifacts_path %></li>
    </ul>
  <% end %>
</div>

app/views/layouts/_uploader.html.erb
<div id="uploader">
  <%= form_for Picture.new do |f| %>
    <div class="file-input">
      <% if mobile_device? %>
      <p class="text">add photo</p>
      <% else %>
      <p class="text">click or drag here</p>
      <% end %>
      <%= f.file_field :image, accept: 'image/jpeg' %>
      <div id="buttons">
         <%= button_tag "cancel", type: "button", class: "cancel" %>
        <%= f.submit "save", class: "submit" %>
      </div>
    </div>
    <%= f.text_field :longitude, value: '', type: 'hidden' %>
    <%= f.text_field :latitude, value: '', type: 'hidden' %><br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>ScrallWall</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <link href='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
  <link href='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'></script>
  <script src='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>


  <%= csrf_meta_tags %>
</head>
<body>
  <div class="overlay"></div>
  <div class="bg"></div>
  <%= render "layouts/header" %>
  <%= yield %>
</body>
</html>